# config map file for PR-Labeler
feature: ['feature/*', 'feat/*']
fix: fix/*
chore: chore/*
ci: ci/*
config: config/*
api: api/*
test: test/*
deps: ['deps/*', 'dep/*']
deploy: deploy/*
docs: docs/*
refractor: refractor/*
revert: revert/*
del: ['remove/*', 'del/*', 'deprecated/*']
fixed-branch: fixed-branch-name
migrate: migrate
